### ISSUE TITLE
easytravel-loadgen - java.lang.IllegalArgumentException: Resource not found: easyTravelConfig.properties

### ISSUE THREAD

**Issue by mariomann** [dynaTrace/Dynatrace-easyTravel-Docker#1]
When I start the easytravel-loadgen docker image it produce the following output:

Exception in thread "main" java.lang.IllegalArgumentException: Resource not found: easyTravelConfig.properties
	at com.dynatrace.easytravel.config.EasyTravelConfig.getAbsolutePropertiesFilePath(EasyTravelConfig.java:773)
	at com.dynatrace.easytravel.config.EasyTravelConfig.create(EasyTravelConfig.java:563)
	at com.dynatrace.easytravel.config.EasyTravelConfig.createSingleton(EasyTravelConfig.java:511)
	at com.dynatrace.easytravel.config.EasyTravelConfig.read(EasyTravelConfig.java:483)
	at com.dynatrace.easytravel.config.EasyTravelConfig.read(EasyTravelConfig.java:453)
	at com.dynatrace.easytravel.util.LocalUriProvider.getURL(LocalUriProvider.java:267)
	at com.dynatrace.diagnostics.uemload.scenarios.EasyTravelHostManager.isApacheWebserver(EasyTravelHostManager.java:91)
	at com.dynatrace.diagnostics.uemload.scenarios.EasyTravel.createVisits(EasyTravel.java:103)
	at com.dynatrace.diagnostics.uemload.scenarios.EasyTravelCustomer.createVisits(EasyTravelCustomer.java:21)
	at com.dynatrace.diagnostics.uemload.UEMLoadScenario.init(UEMLoadScenario.java:47)
	at com.dynatrace.diagnostics.uemload.Simulator.<init>(Simulator.java:53)
	at com.dynatrace.diagnostics.uemload.BrowserSimulator.<init>(BrowserSimulator.java:21)
	at com.dynatrace.diagnostics.uemload.BrowserScenario.createSimulator(BrowserScenario.java:21)
	at com.dynatrace.diagnostics.uemload.CLI.main(CLI.java:145)

Can you provide the file easyTravelConfig.properties

Tank you.

**Comment by metmajer** [comment]
Thanks @mariomann. I am having a look!

**Comment by metmajer** [comment]
@mariomann: the issue has been fixed in commits 20e964b and e0397c3. The image on the Docker Hub has been updated, too.
